project:
  type: website
  output-dir: docs

website:
  title: "Alyssa Counsell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: consulting.qmd
        text: Stats Consulting

format:
  html:
    theme: 
        light: Lumen
        dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

